parameters:
    debug.exceptions: true
    debug.load_time: true
    debug.sql_explain: true
    debug.memory: true
    debug.show_errors: true
    debug.error_handler: false
    twig.debug: false
    twig.auto_reload: false
    twig.enable_debug_extension: false
    session.log_errors: false

