imports:
    - { resource: debug.yml }

services:
    dark1.debug.listener:
        class: dark1\debug\event\listener
        arguments:
            - '@request'
        tags:
            - { name: event.listener }
